name: meditation_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.5
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  go_router: ^13.0.0
  jwt_decoder: ^2.0.1
  video_player: ^2.2.17
  chewie: ^1.0.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
